aws_sg_manage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sgman', include('sgman.urls')),
]

sgman/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

sgman/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
import boto3

AWS_REGIONS = (
    ("us-east-1", "US-EAST-1"),
    ("us-west-1", "US-WEST-1")
)


class VpnSgId(models.Model):
    vpn_sg_id = models.CharField(max_length=50, null=False)
    vpn_sg_region = models.CharField(
        max_length=20,
        choices=AWS_REGIONS,
        default="us-east-1"
    )

    def __str__(self):
        return self.vpn_sg_id


class SgAccess(models.Model):
    sg_rule_id = models.CharField(max_length=50, null=True)
    employee_email = models.EmailField()
    allow_ip = models.GenericIPAddressField()
    datetime_added = models.DateTimeField(default=timezone.now)
    added_by = models.CharField(max_length=50)
    enabled = models.BooleanField(default=False)

    def __str__(self):
        return self.employee_email


@receiver(pre_save, sender=SgAccess, dispatch_uid="pre_save_sgaccess")
def pre_save_sgaccess(sender, instance: SgAccess, **kwargs):
    # Check if Security Group is added by checking Model entry count
    if VpnSgId.objects.count() != 1:
        raise Exception("Please add VPN Security group  and region first!!!")
    vpn_sg_id = VpnSgId.objects.values()[0]['vpn_sg_id']
    vpn_sg_region = VpnSgId.objects.values()[0]['vpn_sg_region']

    ec2client = boto3.client("ec2", region_name=vpn_sg_region)

    if instance._state.adding:
        # Add the new IP received from form in Security Group
        update_sg = ec2client.authorize_security_group_ingress(
            GroupId=vpn_sg_id,
            IpProtocol='TCP',
            CidrIp=instance.allow_ip + "/32",
            FromPort=80,
            ToPort=80,
        )

        # If IP is not added to Security group, raise exception
        if not update_sg['Return']:
            raise Exception("SG was not updated. Please check!!!")

        # Set Security Rule ID in Allow Access model
        instance.sg_rule_id = update_sg['SecurityGroupRules'][0]['SecurityGroupRuleId']
        instance.enabled = True
    else:
        # Remove IP using SG Rule ID received from form in Security Group
        remove_sg_entry = ec2client.revoke_security_group_ingress(
            GroupId=vpn_sg_id,
            SecurityGroupRuleIds=[instance.sg_rule_id],
        )
        if not remove_sg_entry['Return']:
            raise Exception("SG Entry was not Removed. Please check!!!")

sgman/forms.py
from django import forms
from .models import SgAccess


class SgAccessForm(forms.ModelForm):
    class Meta:
        model = SgAccess
        fields = ["employee_email", "allow_ip"]
        labels = {"employee_email": "Employee Email", "allow_ip": "Allow IP"}

    def save(self, **kwargs):
        user = kwargs.pop('user')
        instance = super(SgAccessForm, self).save(**kwargs)
        instance.added_by = user
        instance.save()
        return instance

sgman/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect

from .models import SgAccess
from .forms import SgAccessForm


# Create your views here.
@login_required(login_url="/admin/")
@csrf_exempt
def index(request):
    if request.POST.get("allow_ip"):
        form = SgAccessForm(request.POST or None)
    else:
        form = SgAccessForm(None)
    allowed_sg_list = SgAccess.objects.filter(enabled=True).order_by("-datetime_added")
    context = {
        'sg_access_form': form,
        'allowed_sg_list': allowed_sg_list,
    }

    if form.is_valid() and request.POST.get("allow_ip"):
        form.save(user=request.user, commit=False)
        messages.success(request, 'Employee IP whitelisted successfully.')
        return HttpResponseRedirect("sgman")
    if request.POST.get('delete-id'):
        del_sg_rule = SgAccess.objects.filter(sg_rule_id=request.POST.get('delete-id'))
        del_sg_rule.update(enabled=False)
        SgAccess.objects.get(sg_rule_id=request.POST.get('delete-id')).save(update_fields=['enabled'])
        return HttpResponseRedirect("sgman")

    return render(request, 'sgman/sg_list.html', context)

sgman/templates/sgman/base.html
<!-- sgman/templates/sgman/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Temporary Access</title>
</head>
<body>
    <section class="hero is-small is-success mb-4">
        <div class="hero-body">
            <h1 class="title is-1"></h1>
            <p class="subtitle is-4" align="center">
                Temporary Access via AWS Security Group
            </p>
        </div>
    </section>

    <div>
        {% block content %}

        {% endblock content %}
    </div>

</body>
</html>

sgman/templates/sgman/sg_list.html
<!-- sgman/templates/sgman/sg_list.html -->

{% extends 'sgman/base.html' %}

{% block content %}
<head>
<style>

    .center {
      margin-left: auto;
      margin-right: auto;
      text-align:center;
      width: 21%;
      border: 3px solid green;
      padding: 10px;
    }

    .form {
        text-align: center;
    }

    body {
      font-family: Arial, Helvetica, sans-serif;
    }

    /* Solid border */
    hr.solid {
      border-top: 3px solid #bbb;
    }

    table, td, th {
      border: 1px solid #DDD;
      text-align:center;
      width:14.2%;
      padding:5px;
      white-space: nowrap;
      margin-left: auto;
      margin-right: auto;
    }

</style>
</head>

{% if user.is_authenticated and perms.sgman.change_sgaccess %}

{% if messages %}
<ul class="messages" align='center'>
    {% for message in messages %}
    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}

<div class='center'>
    <form method="POST">
      <div class="inputs" align='right'>
      <fieldset>
        <strong><legend align="center">Enter Employee details</legend></strong><br />
        {{ sg_access_form.as_p }}<br />
        <button type="submit" class='center' >Submit</button>
      </fieldset>
      </div>
    </form>
</div>

<hr class="solid">

<table class="table is-bordered">
  <table class="table">
   <thead>
    <tr>
        <th>Employee Email</th>
        <th>Security Group Rule ID</th>
        <th>Allowed IP</th>
        <th>Added At</th>
        <th>Added By</th>
        <th></th>
    </tr>
  </thead>
    <tr>
        {% for sg in allowed_sg_list %}
        <tr>
        <td>{{ sg.employee_email }}</td>
        <td>{{ sg.sg_rule_id }}</td>
        <td>{{ sg.allow_ip }}</td>
        <td>{{ sg.datetime_added }}</td>
        <td>{{ sg.added_by }}</td>
        <td><form method="POST">
        <input type="hidden" value="{{ sg.sg_rule_id }}" name="delete-id">
        <input type="Submit" value="Delete"></button>
        </form></td>
        </tr>
        {% endfor %}
    </tr>
  </table>
</div>

{% endif %}

{% endblock content %}